Algoritmo "ExercicioCirculo"

// Descrição   : O programa calcula a area de um circulo
//               baseando-se na medida fornecida do raio
// Autor(a)    : Luis Felipe Bandeira Junghans
// Data atual  : 3/12/2023

Var
raio: real
area: real


Inicio
escreva("Digite a medida do raio: ")
leia(raio)


area <- (pi * raio^2)

escreva("A medida da area do circulo eh de ", area:1:3)


Fimalgoritmo