Algoritmo "Teste de mesa 4"

// Descrição   : Gabarito do teste de mesa manual realizado no caderno.
// Data atual  : 21/12/2023

Var
   a, b, i : inteiro
   V, W : vetor [0..6] de inteiro

Inicio

   para a de 0 ate 2 faca
      V[a] <- 5
      W[a] <- a
   fimpara

   escreval("Vetor V")
   para i de 0 ate 2 faca
      escreval(V[i])
   fimpara
   
   escreval("Vetor W")
   para i de 0 ate 2 faca
      escreval(W[i])
   fimpara



Fimalgoritmo